### ISSUE TITLE
Add Central City, Spawn Warps

### ISSUE THREAD

**Issue by Scarycrumb45** [MRT-Map/gatelogue#122]
Central City isn't on the town list, so it's not already included. Also has a ton of warps available - maybe a SpawnWarp node?

**Comment by iiiii7d** [comment]
central city has been added in https://github.com/MRT-Map/gatelogue/commit/424b2d95ae71f9b6f315712512a632f680a23e45

**Comment by iiiii7d** [comment]
spawn warps have been added in https://github.com/MRT-Map/gatelogue/commit/e7f2b7e3ac924f3e921120f229bfa40eb1b9fb83
