### ISSUE TITLE
Town List incorrectly imports blank cells as "nan"

### ISSUE THREAD

**Issue by Scarycrumb45** [MRT-Map/gatelogue#123]
an empty row in the town list is imported as:
```
{"type": "Town", "i": 36671, "source": ["MRT Town List"], "coordinates": null, "world": "New", "proximity": {}, "shared_facility": [], "name": "nan", "rank": "nan", "mayor": "nan", "deputy_mayor": null}
```
note the name and rank specifically. this empty row shouldn't be added to the data.

on the same topic, the town Natal also parses with `"nan"` as the mayor - when it really should parse as `null` or maybe `"Frumple"`

**Comment by iiiii7d** [comment]
fixed in https://github.com/MRT-Map/gatelogue/commit/424b2d95ae71f9b6f315712512a632f680a23e45
