### ISSUE TITLE
AirFlight specifies mode, but does not use it

### ISSUE THREAD

**Issue by Scarycrumb45** [MRT-Map/gatelogue#125]
AirFlight nodes always include `"mode": null` but the value is never populated. If I had to guess by looking at the `AirAirport` nodes, these are intended to contain "seaplane", "helicopter", or "plane"

For example:
```
{"type": "AirFlight", "i": 38896, "source": ["MRT Transit (Air)"], "codes": ["101"], "mode": null, "gates": [2, 8], "airline": 0}}
```

**Comment by iiiii7d** [comment]
mode is now populated by both MRT Transit and inferring from gate size
https://github.com/MRT-Map/gatelogue/commit/16132acf1bff2524e1642cfd0cf909b69224a9fc
